create database casestudy1
use casestudy1

select * from fact
select * from product
select * from location

/*. 1) Display the number of states present in the LocationTable.*/
select count(distinct state) as Number_of_states from location

/*  2) How many products are of regular type?*/
select count (type) as regular_product_count from product 
where type = 'Regular'

/*  3) How much spending has been done on marketing of product ID 1?*/
select productID ,sum(marketing) as total_spending from fact
where productID = 1
group by productID

/*  4) What is the minimum sales of a product*/

select * from fact where sales = (select min(sales) as min_sales from fact)

/*  5) Display the max Cost of Good Sold (COGS).*/
select max(COGS) as max_cogs from fact

/*  6) Display the details of the product where product type is coffee.*/
select * from product where product_type = 'Coffee'

/*  7) Display the details where total expenses are greater than 40*/
select * from fact where Total_Expenses > 40

/*  8) What is the average sales in area code 719?*/

select avg(sales) as avg_sal from fact 
group by area_code
having area_code = 719

/*  9) Find out the total profit generated by Colorado state.*/

select SUM(Profit) as total_profit from fact
inner join Location
on fact.Area_Code=Location.Area_Code
where State='Colorado'

/*  10) Display the average inventory for each product ID*/
select productid , avg(inventory) as avg_in from fact
group by productid

/*  11) Display state in a sequential order in a Location Table.*/
select * from location 
order by state

select * from fact
select * from product
select * from location

/*  12) Display the average budget of the Product where the average budget
margin should be greater than 100*/

select ProductId,AVG(Budget_Margin) as avg_bm from fact
group by ProductId
having AVG(Budget_Margin)>100

/*  13) What is the total sales done on date 2010-01-01?*/
select sum(sales) as total_sales from fact
where date = '2010-01-01'

/*  14) Display the average total expense of each product ID on an individual date.*/
select date , productid ,avg(total_expenses) as avg_exp from fact 
group by productid , date
order by date 

/*   15) Display the table with the following attributes such as 
date, productID, product_type, product, sales, profit, state, area_code*/
select p.product_type , p.product , p.productid,
f.date , f.sales, f.profit, l.state, f.area_code from fact f
inner join product p on f.productId = p.productid
inner join location l
on l.Area_Code = f.Area_Code

select * from fact
select * from product
select * from location

/*16. Display the rank without any gap to show the sales wise rank*/
select *,DENSE_RANK() over (order by sales DESC) as sales_rank from fact 

/*17. Find the state wise profit and sales.*/
select l.state,sum(f.profit) as prof,sum(f.sales) as sal 
from fact f
inner join location l on f.Area_Code = l.Area_Code
group by l.state

/* 18.Find the state wise profit and sales along with the productname.*/
select l.state,sum(f.profit) as prof,sum(f.sales) as sal,p.product 
from fact f
inner join location l on f.Area_Code = l.Area_Code
inner join product p on f.ProductId = p.ProductId
group by l.state , p.Product

/*19. If there is an increase in sales of 5%, calculate the increasedsales*/
select sales , sales + (0.05*sales) as increased_sales from fact

/*20. Find the maximum profit along with the product ID and producttype*/
select max(f.profit) as max_profit , p.productid , p.product_type from fact f
inner join product p on f.ProductId = p.ProductId
group by p.product_type , p.ProductId

/*21. Create a stored procedure to fetch the result according to the 
product typefrom Product Table.*/
create procedure result
@product_type varchar(255)
as
begin
select product , product_type from product
where Product_Type = @product_type 
end

exec result 'coffee'

/*22. Write a query by creating a condition in which if the total expenses 
is lessthan60 then it is a profit or else loss*/
select productid, total_expenses,
case 
when total_expenses < 60 then 'Profit'
else 'Loss' 
end as status_
from fact


select * from fact
select * from product
select * from location

/*23. Give the total weekly sales value with the date and product IDdetails. 
Use roll-up to pull the data in hierarchical order.*/

select DATEPART(week,date) as week_no,date,productid, sum(sales) as total_sales
from fact
group by rollup(datepart(week,date),date,productid)
order by week_no,date,productid

/*24. Apply union and intersection operator on the tables which consist of
attribute area code.*/
select area_code from fact
union
select area_code from location

select area_code from fact
intersect
select area_code from location

/*25. Create a user-defined function for the product table to fetch a particular
product type based upon the user’s preference*/
create function fun(
@protype varchar(255))
returns table 
as 
return 
select product, product_type from product 
where product_type = @protype

select * from fun('coffee')

/*26. Change the product type from coffee to tea where product IDis 1 and undo
it*/
Begin transaction
update product
set product_type = 'Tea'
where ProductId = 1
rollback

/*27. Display the date, product ID and sales where total expenses are
between 100 to 200.*/
select date,productId,sales from fact
where Total_Expenses between 100 and 200

/*28. Delete the records in the Product Table for regular type*/
delete from product where type = 'Regular'

/*29. Display the ASCII value of the fifth character from the columnProduct.*/
select ascii(substring(product,5,1)) as ascii_value
from Product










